# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnaylysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_frames', models.CharField(max_length=20)),
                ('total_duration_sec', models.CharField(max_length=20)),
                ('total_analysed_duration', models.CharField(max_length=35)),
                ('video_path', models.FileField(blank=True, null=True, upload_to='video_to_analysis', verbose_name='Video Analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date & Time')),
            ],
        ),
    ]
